name: Build & push Codespace Image

on:
  push:
    branches:
      - main

env:
  IMAGE_ID: ghcr.io/${{ github.repository }}/codespace

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - run: |
          echo ${{ github.event.pull_request.number || 'latest' }}
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          chmod 0666 Gemfile*
          docker buildx build \
            --push \
            --cache-from=$IMAGE_ID:cache \
            --cache-to type=registry,ref=$IMAGE_ID:cache,mode=max \
            --tag $IMAGE_ID:latest \
            .
